### ISSUE TITLE
LICENSE

### ISSUE THREAD

**Issue by tekacs** [olafurpg/scala-db-codegen#6]
Any chance this project could get a LICENSE file, at all?

Sadly in its current state it's un-forkable, as far as I can tell. I was hoping to work on some updates and extensions. :smile:

Thanks for the great project!

**Comment by olafurpg** [comment]
The lack of a licence was an oversight on my half. The project is a subdirectory of a closed source application I'm working on.

> Thanks for the great project!

It still has some quirks but so far does the job for my needs. Enjoy ^^
